CREATE TABLE [dbo].[PlayerTrack](
	[TrackId] [int] IDENTITY(1,1) NOT NULL,
	[PlayerId] [int] NOT NULL,
	[Track] [varchar](25) NOT NULL,
	[TileId] [int] NOT NULL,
	[Position] [int] NOT NULL,
 CONSTRAINT [PK_PlayerTrack] PRIMARY KEY CLUSTERED 
(
	[TrackId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

