CREATE TABLE [dbo].[Turns](
	[TurnId] [int] IDENTITY(1,1) NOT NULL,
	[PlayerId] [int] NULL,
	[GameId] [int] NULL,
	[Action] [varchar](50) NULL,
 CONSTRAINT [PK_Turns] PRIMARY KEY CLUSTERED 
(
	[TurnId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]