// <auto-generated />
namespace Occultation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EvenMoreDiscoveryTiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EvenMoreDiscoveryTiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201505282003037_EvenMoreDiscoveryTiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
